### ISSUE TITLE
LSST detection probability algorithm

### ISSUE THREAD

**Issue by TomWagg** [dirac-institute/hybrid_sso_catalogue#10]
Need to discuss this with Mario but the current algorithm does the following for each object in a night:

- Get ephemerides for every field time in the next night
- Do this for all variant orbits, i.e. with ra/dec errors and distance/RV grid
- For each field start time `i`, check if the predicted RA/Dec is within 2.1 degrees of the ra/dec of field `i` and field `i - 1`
- For each variant orbit, calculate the fraction of orbits that predict the object will be in a field on the next day and use this as a probability that the object will be seen again

**TODOs**

- [x] #1 
- [x] #9
- [x] Project forward 14 days rather than just 1
- [x] Require two more tracklets that match the usual filters
- [x] #12 
- [x] #15 
- [x] #18
- [x] #19
- [x] #20
- [x] #22
- [x] #24
- [x] #25

**Comment by TomWagg** [comment]
**Questions/Concerns**

- **Speed:** Code currently takes ~20s per object (and this is almost entirely in the ephemerides creation) - is this too slow? Hard to speed it up because it's a black box
- **Fast objects:** Fast objects may not be detected (something that is within a field between the start/end time but not at either time will be missed with the current algorithm)
- **Multiple nights:** Do we want to just do this one night in advance or multiple in the future?
- **Number of observations:** Do I need to account for how many previous observations we have?
    - E.g. if it's been observed 4 times already does it affect probability of sending it to the NEOCP
    - Will things observed 6 times over 3 nights be automatically removed?

**EDIT: Question answers**

- **Speed:** See optimisations below
- **Fast objects:** Don't worry about them, probably aren't any but they'd just be a line anyway
- **Multiple nights:** Multiple! 15, see updates below
- **Number of observations:** Don't worry for now. Definitely don't care about already detected objects. May need to account for things with previous tracklets.

**Comment by TomWagg** [comment]
**Updates that I need to make**

- [x] We're only doing this for objects that have digest2 > 65
- [x] Project forward 14 days rather than just 1
- [x] Require two more tracklets that match the usual filters

**Optimisations**
We don't need to get ephemerides for _every_ visit, just those the tracklet could reach. So work out its velocity from the observation and then given the length of the night, only check the visits that it could possible reach over the course of the night (should go from ~800 to ~10).

I do worry that this means I'll need to get ephemerides twice...but I assume that's still faster

**Comment by TomWagg** [comment]
![image](https://user-images.githubusercontent.com/21990332/188281916-cac20487-25cd-46ae-bff7-5d06ffe190ce.png)

Good progress on including magnitudes. Algorithm now has ~80% success rate, going to investigate some of the outliers.

**Comment by TomWagg** [comment]
I found a small bug and it's actually slightly better (82%)
![image](https://user-images.githubusercontent.com/21990332/188527049-c83538a7-305c-4e9e-afc0-60b0a99ad771.png)

**Comment by TomWagg** [comment]
Here's the results for all NEOs in the first year
![image](https://user-images.githubusercontent.com/21990332/189542667-e1e64099-0cfc-45bb-bfd4-08d70cf5141c.png)
